In [1]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import sys 
import sklearn
import tensorflow as tf
from tensorflow import keras
assert tf.__version__ >="2.4"


#  Tensors and Operations


In [5]:
tf.constant(13)

<tf.Tensor: shape=(), dtype=int32, numpy=13>

In [8]:
m = tf.constant([ [1.,2.,3.], [4.,5.,6.]])
m

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [9]:
m.shape

TensorShape([2, 3])

In [11]:
m.dtype

tf.float32

In [13]:
m[:, 1:]

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [5., 6.]], dtype=float32)>

In [16]:
m[..., 1, tf.newaxis]

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [5.]], dtype=float32)>

In [17]:
import mysql.connector

mydb = mysql.connector.connect(
  host="localhost",
  user="myusername",
  password="mypassword"
)

print(mydb)


ModuleNotFoundError: No module named 'mysql'

In [18]:
!pip install mysql

You should consider upgrading via the 'c:\users\tranli\wdomain\python.exe -m pip install --upgrade pip' command.
